name: Preprocessing Workflow

on:
  push:
    paths:
      - 'preprocessing/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install pandas scikit-learn

      - name: Run Preprocessing Script
        run: |
          python preprocessing/automate_Yorris_Siagian.py

      - name: Upload Preprocessed Dataset
        uses: actions/upload-artifact@v3
        with:
          name: preprocessed-dataset
          path: preprocessing/students_performance_preprocessing.csv
